name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Type of version to bump"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - run: |
          git config user.name 'Lucas Castro'
          git config user.email 'hello+oss@lucasamonrc.dev'

      - name: Create version bump branch
        run: |
          BRANCH_NAME="version-bump-${{ github.event.inputs.version }}-$(date +%s)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - run: npm version ${{ github.event.inputs.version }}
      - run: npm run quality:fix

      - name: Commit and push changes
        run: |
          git push --set-upstream origin $BRANCH_NAME --follow-tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ github.event.inputs.version }}"
          title: "Bump version to ${{ github.event.inputs.version }}"
          body: |
            This PR bumps the version to ${{ github.event.inputs.version }}.

            Created automatically by the Bump version workflow.
          branch: ${{ env.BRANCH_NAME }}
          base: main
